name: 'Postgres Backup and Upload'

on:
  schedule:
    - cron: '0 8 * * *' # 3am cst
  workflow_dispatch:

jobs:
  backup_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Postgres Dump Backup
        uses: tj-actions/pg-dump@v3
        with:
          database_url: ${{ secrets.DATABASE_URL }}
          postgresql_version: '16'
          path: 'backups/backup.sql'
          options: '-O'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload backup to Azure Blob Storage
        run: |
          az storage blob upload \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --container-name ${{ secrets.AZURE_STORAGE_CONTAINER }} \
            --name backup-$(date +%Y-%m-%d-%H-%M-%S).sql \
            --file backups/backup.sql \
            --overwrite true
